apiVersion: v2
name: task-management
description: A Helm chart for Task Management Application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - task-management
  - nodejs
  - react
  - mongodb
maintainers:
  - name: ahmed-226
    url: https://github.com/ahmed-226
home: https://github.com/ahmed-226/Task-Management
sources:
  - https://github.com/ahmed-226/Task-Management
dependencies:
  - name: mongodb
    version: "14.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
