{{- if .Values.client.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "task-management.fullname" . }}-client
  labels:
    {{- include "task-management.labels" . | nindent 4 }}
    component: client
spec:
  {{- if not .Values.client.autoscaling.enabled }}
  replicas: {{ .Values.client.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "task-management.selectorLabels" . | nindent 6 }}
      component: client
  template:
    metadata:
      labels:
        {{- include "task-management.selectorLabels" . | nindent 8 }}
        component: client
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "task-management.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: client
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry }}{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.client.service.targetPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.client.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.client.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.client.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.client.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.client.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.client.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.client.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.client.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.client.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.client.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.client.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.client.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
