{{- if and .Values.mongodb.enabled .Values.mongodb.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-management.fullname" . }}-mongodb-secret
  labels:
    {{- include "task-management.labels" . | nindent 4 }}
    component: mongodb
type: Opaque
data:
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
  {{- if .Values.mongodb.auth.password }}
  mongodb-password: {{ .Values.mongodb.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}
