{{- if and .Values.mongodb.enabled .Values.mongodb.useBuiltIn }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-management.fullname" . }}-mongodb
  labels:
    {{- include "task-management.labels" . | nindent 4 }}
    component: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
  selector:
    {{- include "task-management.selectorLabels" . | nindent 4 }}
    component: mongodb
{{- end }}
