{{- if .Values.server.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-management.fullname" . }}-server-secret
  labels:
    {{- include "task-management.labels" . | nindent 4 }}
    component: server
type: Opaque
data:
  JWT_SECRET: {{ .Values.server.secrets.jwtSecret | b64enc | quote }}
{{- end }}
