apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  labels:
    app: task-management
    component: server
data:
  PORT: "4000"
  NODE_ENV: "production"
  MONGODB_URI: "mongodb://mongodb-service:27017/taskmanagement"
  ALLOWED_ORIGINS: "http://localhost,http://localhost:3000"