apiVersion: v1
kind: Secret
metadata:
  name: server-secret
  labels:
    app: task-management
    component: server
type: Opaque
data:
  # New JWT secret generated after security incident (2025-12-31)
  JWT_SECRET: NjhhNzI2ZjNiNTUzNTA3NTUxNWM0YjU1YTAwODk3OGQxYjhjYTQ0ZGFmMWQxZjE3NDdjMGY1ZjNhZGU3MTNhY2ExMDhhM2IxMzFmNjEwNDY2MzgyYjI1YjliYWUxMjAyNWUwNDcwMTU2ZTQ5ZTlmNjZj
